### ISSUE TITLE
比赛信息未能识别

### ISSUE THREAD

**Issue by danyosate** [NateScarlet/auto-derby#102]
![last_screenshot local](https://user-images.githubusercontent.com/45254054/125438185-aa092ab8-f6a2-48dd-9f5f-2681fda75fc7.png)
Traceback (most recent call last):
  File "K:\Game\uma\auto-derby-master\auto_derby\__main__.py", line 115, in <module>
    main()
  File "K:\Game\uma\auto-derby-master\auto_derby\__main__.py", line 87, in main
    job()
  File "K:\Game\uma\auto-derby-master\auto_derby\jobs\nurturing.py", line 335, in nurturing
    _handle_training(ctx)
  File "K:\Game\uma\auto-derby-master\auto_derby\jobs\nurturing.py", line 126, in _handle_training
    _choose_race(ctx, r)
  File "K:\Game\uma\auto-derby-master\auto_derby\jobs\nurturing.py", line 52, in _choose_race
    if _current_race(ctx) == race1:
  File "K:\Game\uma\auto-derby-master\auto_derby\jobs\nurturing.py", line 30, in _current_race
    race1 = race.find_by_race_detail_image(ctx, template.screenshot())
  File "K:\Game\uma\auto-derby-master\auto_derby\single_mode\race.py", line 799, in find_by_race_detail_image
    raise ValueError("find_by_race_details_image: can race match spec: %s", full_spec)
ValueError: ('find_by_race_details_image: can race match spec: %s', ('札幌', 1, 2600, 1, 1, 1400))

**Comment by NateScarlet** [comment]
这个是 ocr_labels.json 输入错误的标注导致的 重新手动标注解决了
