### ISSUE TITLE
育成開啟粉絲數界面時就停住了

### ISSUE THREAD

**Issue by Kurisu3071** [NateScarlet/auto-derby#114]
```
INFO  [19https://cdn.discordapp.com/emojis/713102857888464926.gif?v=1&size=40 40]:auto_derby.template:181: match: tmpl=tmpl<single_mode_command_training.png>, pos=(199, 760), similarity=0.97
INFO  [19https://cdn.discordapp.com/emojis/713102857888464926.gif?v=1&size=40 41]:auto_derby.template:181: match: tmpl=tmpl<single_mode_character_detail_button.png>, pos=(466, 559), similarity=0.96
INFO  [19https://cdn.discordapp.com/emojis/713102857888464926.gif?v=1&size=40 44]:auto_derby.template:181: match: tmpl=tmpl<single_mode_class_detail_button.png>, pos=(115, 155), similarity=0.91
INFO  [19https://cdn.discordapp.com/emojis/713102857888464926.gif?v=1&size=40 56]:auto_derby.template:181: match: tmpl=tmpl<single_mode_class_detail_title.png>, pos=(172, 226), similarity=0.97
INFO  [19https://cdn.discordapp.com/emojis/713102857888464926.gif?v=1&size=40 59]:auto_derby.template:181: match: tmpl=tmpl<close_button.png>, pos=(250, 676), similarity=1.00
ERROR [19https://cdn.discordapp.com/emojis/713102869682978836.gif?v=1&size=40 09]:main:124: unexpected exception
Traceback (most recent call last):
  File "D:\auto-derby-master\auto_derby__main.py", line 120, in <module>
    main()
  File "D:\auto-derby-master\auto_derby__main.py", line 91, in main
    job()
  File "D:\auto-derby-master\auto_derby\jobs\nurturing.py", line 362, in nurturing
    _update_context_by_command_scene(ctx)
  File "D:\auto-derby-master\auto_derby\jobs\nurturing.py", line 306, in _update_context_by_command_scene
    _update_context_by_class_menu(ctx)
  File "D:\auto-derby-master\auto_derby\jobs\nurturing.py", line 291, in _update_context_by_class_menu
    action.wait_tap_image(templates.CLOSE_BUTTON)
  File "D:\auto-derby-master\auto_derby\action.py", line 80, in wait_tap_image
    tap((pos[0] + x, pos[1] + y))
  File "D:\auto-derby-master\auto_derby\action.py", line 18, in tap
    clients.current().tap(point)
  File "D:\auto-derby-master\auto_derby\clients\adb.py", line 56, in tap
    res = self.device.shell(command)
  File "C:\Users\maple\AppData\Local\Programs\Python\Python38\lib\site-packages\adb_shell\adb_device.py", line 446, in shell
    return self._service(b'shell', command.encode('utf8'), transport_timeout_s, read_timeout_s, timeout_s, decode)
  File "C:\Users\maple\AppData\Local\Programs\Python\Python38\lib\site-packages\adb_shell\adb_device.py", line 334, in _service
    return b''.join(self._streaming_command(service, command, adb_info)).decode('utf8')
  File "C:\Users\maple\AppData\Local\Programs\Python\Python38\lib\site-packages\adb_shell\adb_device.py", line 1027, in _streaming_command
    for data in self._read_until_close(adb_info):
  File "C:\Users\maple\AppData\Local\Programs\Python\Python38\lib\site-packages\adb_shell\adb_device.py", line 962, in _read_until_close
    cmd, data = self._read_until([constants.CLSE, constants.WRTE], adb_info)
  File "C:\Users\maple\AppData\Local\Programs\Python\Python38\lib\site-packages\adb_shell\adb_device.py", line 918, in _read_until
    cmd, remote_id2, local_id2, data = self._read(expected_cmds, adb_info)
  File "C:\Users\maple\AppData\Local\Programs\Python\Python38\lib\site-packages\adb_shell\adb_device.py", line 866, in _read
    msg = self._transport.bulk_read(constants.MESSAGE_SIZE, adb_info.transport_timeout_s)
  File "C:\Users\maple\AppData\Local\Programs\Python\Python38\lib\site-packages\adb_shell\transport\tcp_transport.py", line 120, in bulk_read
    raise TcpTimeoutException(msg)
adb_shell.exceptions.TcpTimeoutException: Reading from 127.0.0.1:59865 timed out (10.0 seconds)
```
請問要如何解決

**Comment by NateScarlet** [comment]
你这是adb连接断了 重连再试

**Comment by Kurisu3071** [comment]
謝謝，我再試試
