### ISSUE TITLE
黃金城市出道賽

### ISSUE THREAD

**Issue by Small-Ku** [NateScarlet/auto-derby#204]
![last_screenshot](https://user-images.githubusercontent.com/16464896/137458280-2671ce6c-737a-4378-9fcc-641e2b2bfc9b.png)
```
ERROR [2021-10-15 16:33:31]:__main__:123: unexpected exception
Traceback (most recent call last):
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 119, in <module>
    main()
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 90, in main
    job()
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 225, in nurturing
    spec[_spec_key(tmpl)](ac)
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 120, in _handle_target_race
    commands.RaceCommand(scene.first_race(ctx), selected=True).execute(ctx)
  File "D:\dev\auto-derby\auto_derby\scenes\single_mode\race_menu.py", line 69, in first_race
    return next(find_by_race_menu_image(ctx, template.screenshot()))[0]
  File "D:\dev\auto-derby\auto_derby\single_mode\race\game_data.py", line 263, in find_by_race_menu_image
    for i in _find_by_race_menu_item(ctx, screenshot.crop(bbox)):
  File "D:\dev\auto-derby\auto_derby\single_mode\race\game_data.py", line 248, in _find_by_race_menu_item
    raise ValueError("_find_by_race_menu_item: no race match spec: %s", full_spec)
ValueError: ('_find_by_race_menu_item: no race match spec: %s', ((1, 0, 0), '札幌', 1, 1500, 1, 1, 700, (900, 800)))
```

**Comment by NateScarlet** [comment]
这个应该运行下比赛数据更新的脚本就能好

```
py -3.8 ./scripts/extract_single_mode_races.py
```

**Comment by Small-Ku** [comment]
是的，運行後就好了
