### ISSUE TITLE
支持剧本 “Make a new track!!  ～クライマックス開幕”

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#247]
正在 `scenario-climax` 分支进行开发

**Comment by Small-Ku** [comment]
跑完第一場比賽，停在這個畫面時：
![last_screenshot](https://user-images.githubusercontent.com/16464896/155899848-d6cf2bad-6ba0-45c0-89c1-fd7234fd00dd.png)
腳本卻在找cancel_button
應該是[這行](https://github.com/NateScarlet/auto-derby/blob/39bd799527d611327c4aa945f4ec14f982f47272/auto_derby/single_mode/commands/race.py#L53)？
```
DEBUG [04:59:51]:auto_derby.template:47: screenshot
DEBUG [04:59:51]:auto_derby.template:179: not match: tmpl=tmpl<cancel_button.png>, pos=(120, 869), similarity=0.542
INFO  [04:59:51]:auto_derby.template:199: no match: tmpl=('cancel_button.png',)
DEBUG [04:59:51]:auto_derby.template:47: screenshot
DEBUG [04:59:51]:auto_derby.template:179: not match: tmpl=tmpl<cancel_button.png>, pos=(120, 869), similarity=0.542
INFO  [04:59:51]:auto_derby.template:199: no match: tmpl=('cancel_button.png',)
DEBUG [04:59:51]:auto_derby.template:47: screenshot
DEBUG [04:59:51]:auto_derby.template:179: not match: tmpl=tmpl<cancel_button.png>, pos=(120, 869), similarity=0.542
INFO  [04:59:51]:auto_derby.template:199: no match: tmpl=('cancel_button.png',)
DEBUG [04:59:51]:auto_derby.template:47: screenshot
DEBUG [04:59:51]:auto_derby.template:179: not match: tmpl=tmpl<cancel_button.png>, pos=(120, 869), similarity=0.542
INFO  [04:59:51]:auto_derby.template:199: no match: tmpl=('cancel_button.png',)
```

**Comment by NateScarlet** [comment]
@Small-Ku 还没弄好

**Comment by Small-Ku** [comment]
有需要Lose/Draw/Win的截圖用作template嗎?
![Screenshot_2022 02 24_18 09 00 947](https://user-images.githubusercontent.com/16464896/156023845-19427ecd-0641-4062-99e8-39fc9e61caf3.png)
![Screenshot_2022 02 24_18 09 33 509](https://user-images.githubusercontent.com/16464896/156023859-d99d2d97-4e8a-4ade-a2d8-5155dcf1c6df.png)
![Screenshot_2022 02 24_18 19 55 634](https://user-images.githubusercontent.com/16464896/156023866-33e13749-785f-4a7c-aa83-ebdef01d51d1.png)
我的模擬器貌似渲染有問題就是了 XD

**Comment by Small-Ku** [comment]
貌似點數上千時，逗號會導致無法將字串轉換成數字？
![last_screenshot](https://user-images.githubusercontent.com/16464896/156024712-f4b02a4e-942b-4ddf-b136-600468d83dd1.png)
```
DEBUG [00:53:12]:auto_derby.ocr:372: ocr result: 1,057
ERROR [00:53:12]:__main__:123: unexpected exception
Traceback (most recent call last):
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 119, in <module>
    main()
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 90, in main
    job()
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 228, in nurturing
    spec[_spec_key(tmpl)](ac)
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 88, in _ac_handle_turn
    _handle_turn(ac.ctx)
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 41, in _handle_turn
    scene.recognize(ctx)
  File "D:\dev\auto-derby\auto_derby\scenes\single_mode\command.py", line 180, in recognize
    _recognize_shop_coin(ctx)
  File "D:\dev\auto-derby\auto_derby\scenes\single_mode\command.py", line 61, in _recognize_shop_coin
    ctx.shop_coin = int(text)
ValueError: invalid literal for int() with base 10: '1,057'

```

**Comment by NateScarlet** [comment]
因为我自己一边买道具一边用脚本 所以没到过1000，我加个替换就行了

**Comment by Small-Ku** [comment]
![last_screenshot](https://user-images.githubusercontent.com/16464896/156162774-146da5ec-8a6b-470b-956e-d61566f2a2af.png)
按鈕文字跟race_start和single_mode_race_start好像都不一樣呢

**Comment by NateScarlet** [comment]
@Small-Ku [FAQ](https://github.com/NateScarlet/auto-derby/wiki/FAQ#%E8%84%9A%E6%9C%AC%E5%81%9C%E4%BD%8F%E4%BA%86)

我的意见是 第一次打的比赛没必要自动

**Comment by Small-Ku** [comment]
![Firefox accessing 127.0.0.1:4045](https://user-images.githubusercontent.com/16464896/156995180-69e83b47-927e-4906-b58f-d381f773b64b.png)
抽到4045 port訪問不了

**Comment by NateScarlet** [comment]
用 edge 试试

**Comment by NateScarlet** [comment]
我之后加个端口自动选择范围限制

**Comment by Small-Ku** [comment]
剛才有用Edge試了也是不行，不過沒有截圖。不過已經重開了。

**Comment by NateScarlet** [comment]
之后改成用 8300 端口后的首个可用端口好了，ハチミだけに

**Comment by Small-Ku** [comment]
還有OCR識別的問題
![1fb6d7f7ebaa9a230664fd927dd9b](https://user-images.githubusercontent.com/16464896/157038895-83a6704b-14a2-45fb-ad0a-708babff7116.png)
![252c6bcccf063ddeda21f11c3056e530](https://user-images.githubusercontent.com/16464896/157038955-ec24915e-1031-4a00-bd14-896cd3bc0634.png)

**Comment by issenn** [comment]
无法识别 “目标成绩Pt不足”，templates 里没有这个模板。
另外一直没有参加比赛获取Pt，是逻辑上这么设定的么？

**Comment by NateScarlet** [comment]
@issenn 看本issue的第一句话

**Comment by Small-Ku** [comment]
點數OCR貌似還沒有處理減價的情況？
![25f20647a8121d1ff5d5f71f5bd71ecd](https://user-images.githubusercontent.com/16464896/157244111-cdbbbc76-280b-4f09-b6d8-bf6e7dd215f9.png)
![last_screenshot](https://user-images.githubusercontent.com/16464896/157244138-9020b1bf-2350-42c1-9dd1-bad67e405206.png)

**Comment by OokinaSekai** [comment]
![image](https://user-images.githubusercontent.com/61344928/157267985-136d3990-5611-4635-8ab7-35b446eeb4fb.png)
![image](https://user-images.githubusercontent.com/61344928/157268376-d1d5ba49-3ac3-48e6-a82f-d9bf989717cf.png)
开始育成时如果还没开启商店，似乎会一直寻找商店按钮

**Comment by NateScarlet** [comment]
先不急着反馈 我自己都没带商店跑完一次

**Comment by NateScarlet** [comment]
@OokinaSekai 这个是在找物品栏按钮 我加个条件

**Comment by NateScarlet** [comment]
@Small-Ku 适配了打折

**Comment by NateScarlet** [comment]
带商店跑完了一次 剩了39个道具 因为现在只会直接在商店用物品

**Comment by Small-Ku** [comment]
![last_screenshot](https://user-images.githubusercontent.com/16464896/157604632-f9df7560-65ae-4529-9a54-94d045b0c2b3.png)
![b3940f41907e031c1d186fb2e6ce6218](https://user-images.githubusercontent.com/16464896/157604732-364d13df-2527-4c68-aac3-92871fb04d45.png)
```
INFO  [2022-03-10 14:02:12]:auto_derby.template:183: match: tmpl=tmpl<exchange_button.png>, pos=(437, 785), similarity=0.95
DEBUG [2022-03-10 14:02:12]:auto_derby.template:179: not match: tmpl=tmpl<exchange_button.png>, pos=(286, 925), similarity=0.555
DEBUG [2022-03-10 14:02:12]:auto_derby.single_mode.item.label:74: match label: search=08000802080718063f047f007f201860083008380c380c1c0c1e060e0606060200003e3e7e7e200c000c000c7f7e7f7f7e7f080c080c0c0c0c0c042c067c0438100018201830187e7efe7f7e7e3818381838183c182c082e0c260c220c20042000000030003c003c003c003c7e3cfeb47eb400f400f400f60076003600360010, result=ImageHashMapQueryResult<0c000c030c070c067f003f203f200c300c300c380c1c041e060e06070602000000007e3e3e3e200c000c7f0c7f7f7e7f187f080c0c0c0c0c040c043c06380000182018201830187e7e7e7e7e7e381838183c182c082e08260c260c220420002000300034003c003c00340034fe34feb47eb400f400f400760076003600300000:36:0.850>
DEBUG [2022-03-10 14:02:12]:auto_derby.ocr:128: match label: value=3, current=f81ffc3f7c7e007c007c007ec03fc03fc03f007e00f800f80cf8fefffe3ff81f, match=f00ffe3f1ffe00fc00f8007c003fc03f807f00fc00f800f800f87ffffe7ff81f, similarity=0.820
DEBUG [2022-03-10 14:02:12]:auto_derby.ocr:128: match label: value=6, current=f01ff83f3c3c1e001f001f00ff1fff3f3f7c1ff01ff01ff01ef07c7cf83ff00f, match=e00ff83f3c3c1e000f000f00cf1fff3f3f7c1f701f701f701f783e7cf83fe01f, similarity=0.875
DEBUG [2022-03-10 14:02:12]:auto_derby.ocr:339: ocr result: 36
DEBUG [2022-03-10 14:02:12]:auto_derby.single_mode.item.label:74: match label: search=0000c400ecf96ef8661846184618c618c618c600c600c701838183c183c100c0000000000700070006000600c63fc67fc73f070003000300030001000000000004001e101a90ded2fec3fee1fef1fef29ef39ef19ef18cf19ef1fef3ecb30c91010c1f7c03ff03fc03ff191c1d7f1b1e1b1e8bff0b000b7f896389618d7f8d7f, result=ImageHashMapQueryResult<8001c401ecf96cf864f844184418c618c608c600c600c701c78183c183c100c0000000000700070007000600c63fc63fc73fc73f03000300030001000000000000005e101a90ded2fed3fef1fef1fef09ef19ef19ef18cf1bef1fef3ec930c9101081f7f03ff03ff037f097f1d7f197f8bff0b7f0b7f0b7f0b7f0841087f087f:8:0.854>
DEBUG [2022-03-10 14:02:12]:auto_derby.ocr:128: match label: value=1, current=00fc80fff0fffefffeff80ff00ff00ff00ff00ff00ff00ff00ff00ff00fe00fc, match=003ec0fff8fffffffffff0ff80ff00ff00ff00ff00ff00ff00ff00ff00fe003c, similarity=0.898
DEBUG [2022-03-10 14:02:12]:auto_derby.ocr:128: match label: value=3, current=f81ffc3f3c3e007c007c003ec01fe01fe03f007e00f800f80cf8fffffe3ffc1f, match=f81ffc3f1c7e007c007c003c801fe00fe03f00fc00f800f81ffc3ffeff7ffc1f, similarity=0.875
DEBUG [2022-03-10 14:02:12]:auto_derby.ocr:339: ocr result: 13
DEBUG [2022-03-10 14:02:12]:auto_derby.single_mode.item.label:74: match label: search=00083f183ff838fc10cc10c618c618da18781c783c703e7026306338431c400c00807880f881f08180f000f870f8f8c0f08180c000c038c0fcc0fc61e06180614004e085a0c5e0d5e71fe79fe38fe19fe0dde0cde0cdc08ce08de09fc09fc08804183c780cfe0ef80efe273c357e3f3c2f3c2fff2d00257e25662542347e347e, result=ImageHashMapQueryResult<00083f183ff838fc10cc10c618c618da18781c783c703e7026306338431c400c00807880f881c08180f000f870f8f8c0f08180c000c038c07cc0fc61f06180614004e085a1c5e1d5e71fe79fe38fe19fe0dde0cde08dc08ce08de09fc09fc08a04183c7e0cfe0efe0e7e277e357e277e2fff2f7e2f7e2d7e257e2542347e347e:7:0.932>
DEBUG [2022-03-10 14:02:12]:auto_derby.ocr:128: match label: value=1, current=00fc80fff0fffefffeff80ff00ff00ff00ff00ff00ff00ff00ff00ff00fe00fc, match=003ec0fff8fffffffffff0ff80ff00ff00ff00ff00ff00ff00ff00ff00fe003c, similarity=0.898
DEBUG [2022-03-10 14:02:12]:auto_derby.ocr:128: match label: value=3, current=f81ffc3f3c3e007c007c003ec01fe01fe03f007e00f800f80cf8fffffe3ffc1f, match=f81ffc3f1c7e007c007c003c801fe00fe03f00fc00f800f81ffc3ffeff7ffc1f, similarity=0.875
DEBUG [2022-03-10 14:02:12]:auto_derby.ocr:339: ocr result: 13
DEBUG [2022-03-10 14:02:12]:auto_derby.single_mode.item.label:74: match label: search=08000800fe18bf189c1818183c18fc18fe189f198b19891989f9cb70ef706c0000008001c301c301c700c600c600c620c420cc30cc30cc318c39801f801f000f000000b086b086308631863186f186e106f106f306f306e33ee23ce01cb000b009021f061f7f0f7f890d0b091f099f1d9fff9dff1f089f499749954d9f7f9f7f, result=ImageHashMapQueryResult<00000800fc10be189e1808183818fc18fe188f188b1989198b79cb70ef304c00000080018301c300c700c600c600c600c420c420cc30cc318c39801f001f000e000000b084b086308631863186b186e106f106f106fb06e33ee31ca01cb000b009021f061f7f091f000909081f089fff95ff1f7f1f089f089549954d9f7f9f61:24:0.895>
DEBUG [2022-03-10 14:02:12]:auto_derby.ocr:128: match label: value=ト, current=00000c003f00ff00ff07ff1fff7fffffffffff7fff1fff07ff003f000f000000, match=0700070007000f00ff00ff07ff3fffffcfff07fe070007000700070007000700, similarity=0.547
```
這跟我用較低的模擬器分辨率有關嗎？

**Comment by NateScarlet** [comment]
@Small-Ku 应该是一位数价格的宽度太小导致的

现在的实现是取粉色内容边界框的右半边作为价格文本来识别

**Comment by Small-Ku** [comment]
有機會直接先移除那個三角形的灰色再識別嗎 😂
畢竟那個三角形的顏色和文字不相同

**Comment by NateScarlet** [comment]
两个颜色太相似了 不同设备都会有轻微差别

我之后改成用竖向收边把左边的横杠删掉

**Comment by Small-Ku** [comment]
不知道爲什麼明明畫面能看到在找的スタミナ戦術書，但是腳本一直在往上滑
[debug.1.zip](https://github.com/NateScarlet/auto-derby/files/8223793/debug.1.zip)

**Comment by Small-Ku** [comment]
還有可能是系統卡了，沒有按到交換按鈕
```
INFO  [2022-03-10 21:33:47]:auto_derby.scenes.single_mode.shop:158: exchange: Item<リセットホイッスル#42@18>
DEBUG [2022-03-10 21:33:47]:auto_derby.clients.adb:55: tap: input tap 437 642
DEBUG [2022-03-10 21:33:49]:auto_derby.template:47: screenshot
DEBUG [2022-03-10 21:33:49]:auto_derby.template:124: lightness match: tmpl=tmpl<single_mode_shop_use_confirm_button.png>, similarity=1.000
INFO  [2022-03-10 21:33:49]:auto_derby.template:183: match: tmpl=tmpl<single_mode_shop_use_confirm_button.png>, pos=(339, 625), similarity=0.95
DEBUG [2022-03-10 21:33:49]:auto_derby.template:47: screenshot
DEBUG [2022-03-10 21:33:49]:auto_derby.template:124: lightness match: tmpl=tmpl<close_button.png>, similarity=0.998
INFO  [2022-03-10 21:33:49]:auto_derby.template:183: match: tmpl=tmpl<close_button.png>, pos=(131, 613), similarity=0.91
DEBUG [2022-03-10 21:33:49]:auto_derby.template:47: screenshot
DEBUG [2022-03-10 21:33:49]:auto_derby.template:124: lightness match: tmpl=tmpl<close_button.png>, similarity=0.998
INFO  [2022-03-10 21:33:49]:auto_derby.template:183: match: tmpl=tmpl<close_button.png>, pos=(131, 613), similarity=0.91
DEBUG [2022-03-10 21:33:49]:auto_derby.clients.adb:55: tap: input tap 131 613
DEBUG [2022-03-10 21:33:50]:auto_derby.single_mode.item.label:74: match label: search=001000120f330ff30bf989f989b1c9a1c9a149a14921092109210f210f210021009818c91cc91ccd1ccf1c471c631ce35c817c813c813e813e831e8f1ecf08c60000006c032c030c03080206fa66fb6efb7c0330033001180118019c008c0004000000f000f000f007400740c743e443c4630460046004f00ff00f980f980080, result=ImageHashMapQueryResult<000000120f330ff30bf989f989b1c9a1c9a149e14921092109210f210f210021009818c91cc91ccd1ccf1c471c671ca35c817c813c813e813e831e8f1ecf08c60000006c032c030c03080206fa66fb6efb64fb30033001180118019c008c0004000000f000f000f007400740c743e443e463c463046004f00ff00f980f980080:19:0.969>
DEBUG [2022-03-10 21:33:50]:auto_derby.ocr:128: match label: value=7, current=fc3ffffffffffe7f003f801fc00fc007e007e003f003f001f801f801f001f000, match=fe7ffffffffffcff003f001f800fc00fc007e003e003f003f003f003f001f000, similarity=0.891
DEBUG [2022-03-10 21:33:50]:auto_derby.ocr:128: match label: value=0, current=e007f81ffc3f7e7e1ff81ff81ff81ff81ff81ff81ff81ff83e7cfc3ff81ff00f, match=e007f81f7c3f3c3c1e781e780f780ff80ff81ff81ff81f783e7cfc3ff81ff00f, similarity=0.891
DEBUG [2022-03-10 21:33:50]:auto_derby.ocr:339: ocr result: 70
INFO  [2022-03-10 21:33:50]:auto_derby.scenes.single_mode.shop:158: exchange: Item<ロイヤルビタージュース#19@70>
DEBUG [2022-03-10 21:33:50]:auto_derby.clients.adb:55: tap: input tap 437 750
DEBUG [2022-03-10 21:33:52]:auto_derby.template:47: screenshot
DEBUG [2022-03-10 21:33:52]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_shop_use_confirm_button.png>, pos=(145, 911), similarity=0.624
DEBUG [2022-03-10 21:33:52]:auto_derby.template:179: not match: tmpl=tmpl<close_button.png>, pos=(183, 401), similarity=0.564
INFO  [2022-03-10 21:33:52]:auto_derby.template:199: no match: tmpl=('single_mode_shop_use_confirm_button.png', 'close_button.png')
DEBUG [2022-03-10 21:33:52]:auto_derby.template:47: screenshot
DEBUG [2022-03-10 21:33:52]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_shop_use_confirm_button.png>, pos=(145, 911), similarity=0.624
DEBUG [2022-03-10 21:33:52]:auto_derby.template:179: not match: tmpl=tmpl<close_button.png>, pos=(183, 401), similarity=0.564
INFO  [2022-03-10 21:33:52]:auto_derby.template:199: no match: tmpl=('single_mode_shop_use_confirm_button.png', 'close_button.png')
DEBUG [2022-03-10 21:33:52]:auto_derby.template:47: screenshot
DEBUG [2022-03-10 21:33:52]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_shop_use_confirm_button.png>, pos=(145, 911), similarity=0.624
DEBUG [2022-03-10 21:33:52]:auto_derby.template:179: not match: tmpl=tmpl<close_button.png>, pos=(183, 401), similarity=0.564
INFO  [2022-03-10 21:33:52]:auto_derby.template:199: no match: tmpl=('single_mode_shop_use_confirm_button.png', 'close_button.png')
DEBUG [2022-03-10 21:33:52]:auto_derby.template:47: screenshot
DEBUG [2022-03-10 21:33:52]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_shop_use_confirm_button.png>, pos=(145, 911), similarity=0.624
DEBUG [2022-03-10 21:33:52]:auto_derby.template:179: not match: tmpl=tmpl<close_button.png>, pos=(183, 401), similarity=0.564
INFO  [2022-03-10 21:33:52]:auto_derby.template:199: no match: tmpl=('single_mode_shop_use_confirm_button.png', 'close_button.png')
……
```

**Comment by NateScarlet** [comment]
日志显示已经用了 スタミナ戦術書 应该是在找 バイタル20

**Comment by Small-Ku** [comment]
那應該是因爲我不小心按到交換其他物品了吧 XD

**Comment by NateScarlet** [comment]
@Small-Ku 你自己系统卡就再把等待时间调长点 #219

**Comment by Small-Ku** [comment]
可是其他操作沒有這個問題的說，就只有這邊會

**Comment by NateScarlet** [comment]
你用DMM端能复现吗？

**Comment by Small-Ku** [comment]
我試試，很久沒有用 DMM 端了

**Comment by Small-Ku** [comment]
DMM版也出現了這樣的情況
[debug.zip](https://github.com/NateScarlet/auto-derby/files/8224188/debug.zip)
```
INFO  [2022-03-10 22:30:16]:auto_derby.scenes.single_mode.shop:158: exchange: Item<スピード戦術書#6@15>
DEBUG [2022-03-10 22:30:16]:auto_derby.clients.dmm:61: tap: point=(436, 750)
DEBUG [2022-03-10 22:30:16]:auto_derby.window:133: foreground window: h_wnd=1706880
DEBUG [2022-03-10 22:30:17]:auto_derby.window:112: set foreground window: h_wnd=1706880
DEBUG [2022-03-10 22:30:17]:auto_derby.template:47: screenshot
DEBUG [2022-03-10 22:30:17]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_shop_use_confirm_button.png>, pos=(145, 911), similarity=0.625
DEBUG [2022-03-10 22:30:17]:auto_derby.template:179: not match: tmpl=tmpl<close_button.png>, pos=(390, 91), similarity=0.555
INFO  [2022-03-10 22:30:17]:auto_derby.template:199: no match: tmpl=('single_mode_shop_use_confirm_button.png', 'close_button.png')
DEBUG [2022-03-10 22:30:17]:auto_derby.template:47: screenshot
DEBUG [2022-03-10 22:30:17]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_shop_use_confirm_button.png>, pos=(145, 911), similarity=0.625
DEBUG [2022-03-10 22:30:17]:auto_derby.template:179: not match: tmpl=tmpl<close_button.png>, pos=(390, 91), similarity=0.555
INFO  [2022-03-10 22:30:17]:auto_derby.template:199: no match: tmpl=('single_mode_shop_use_confirm_button.png', 'close_button.png')
DEBUG [2022-03-10 22:30:17]:auto_derby.template:47: screenshot
DEBUG [2022-03-10 22:30:17]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_shop_use_confirm_button.png>, pos=(145, 911), similarity=0.625
DEBUG [2022-03-10 22:30:17]:auto_derby.template:179: not match: tmpl=tmpl<close_button.png>, pos=(390, 91), similarity=0.555
INFO  [2022-03-10 22:30:17]:auto_derby.template:199: no match: tmpl=('single_mode_shop_use_confirm_button.png', 'close_button.png')
DEBUG [2022-03-10 22:30:18]:auto_derby.template:47: screenshot
DEBUG [2022-03-10 22:30:18]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_shop_use_confirm_button.png>, pos=(145, 911), similarity=0.625
DEBUG [2022-03-10 22:30:18]:auto_derby.template:179: not match: tmpl=tmpl<close_button.png>, pos=(390, 91), similarity=0.555
INFO  [2022-03-10 22:30:18]:auto_derby.template:199: no match: tmpl=('single_mode_shop_use_confirm_button.png', 'close_button.png')
```

**Comment by NateScarlet** [comment]
可能是滚动到头之后反弹动画导致的

**Comment by Small-Ku** [comment]
卡在神奇的地方了，不知道爲什麼按鈕變灰了，[看不懂日文](https://user-images.githubusercontent.com/16464896/157908656-88b5a646-de4a-4cad-9eb2-9dba3585e8b3.png)
[last_screenshot](https://user-images.githubusercontent.com/16464896/157908408-d92878b6-9a70-4564-9303-ca0bbb7e1aaf.png)
```
DEBUG [2022-03-12 00:25:02]:auto_derby.template:124: lightness match: tmpl=tmpl<single_mode_item_list_use_button.png>, similarity=0.767
DEBUG [2022-03-12 00:25:02]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_item_list_use_button.png>, pos=(414, 43), similarity=0.974
INFO  [2022-03-12 00:25:02]:auto_derby.template:199: no match: tmpl=('single_mode_item_list_use_button.png',)
INFO  [2022-03-12 00:25:02]:auto_derby.scenes.single_mode.item_list:169: use: Item<チアメガホン#43x1>
DEBUG [2022-03-12 00:25:02]:auto_derby.clients.adb:55: tap: input tap 437 342
DEBUG [2022-03-12 00:25:03]:auto_derby.template:47: screenshot
DEBUG [2022-03-12 00:25:03]:auto_derby.template:61: load: single_mode_item_use_button.pos.png
DEBUG [2022-03-12 00:25:03]:auto_derby.template:78: can not load: single_mode_item_use_button.pos.png: [Errno 2] No such file or directory: 'D:\\dev\\auto-derby\\auto_derby\\templates\\single_mode_item_use_button.pos.png'
DEBUG [2022-03-12 00:25:03]:auto_derby.template:61: load: single_mode_item_use_button.png
DEBUG [2022-03-12 00:25:03]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_item_use_button.png>, pos=(139, 929), similarity=0.489
INFO  [2022-03-12 00:25:03]:auto_derby.template:199: no match: tmpl=('single_mode_item_use_button.png',)
DEBUG [2022-03-12 00:25:03]:auto_derby.template:47: screenshot
DEBUG [2022-03-12 00:25:03]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_item_use_button.png>, pos=(139, 929), similarity=0.489
INFO  [2022-03-12 00:25:03]:auto_derby.template:199: no match: tmpl=('single_mode_item_use_button.png',)
DEBUG [2022-03-12 00:25:04]:auto_derby.template:47: screenshot
DEBUG [2022-03-12 00:25:04]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_item_use_button.png>, pos=(139, 929), similarity=0.489
INFO  [2022-03-12 00:25:04]:auto_derby.template:199: no match: tmpl=('single_mode_item_use_button.png',)
……
```

**Comment by NateScarlet** [comment]
相同效果类型的物品不能重复使用 这个我正在弄

**Comment by Small-Ku** [comment]
[debug.zip](https://github.com/NateScarlet/auto-derby/files/8234186/debug.zip)
```
INFO  [2022-03-12 01:40:04]:auto_derby.jobs.nurturing:56: shop items
INFO  [2022-03-12 01:40:04]:auto_derby.jobs.nurturing:69: score:	0.00/0.00:	Item<うるおいハンドクリーム#32@15>	
INFO  [2022-03-12 01:40:04]:auto_derby.jobs.nurturing:69: score:	0.00/0.00:	Item<リセットホイッスル#42@20>	
INFO  [2022-03-12 01:40:04]:auto_derby.jobs.nurturing:69: score:	0.00/0.00:	Item<プレーンカップケーキ#22@30>	
INFO  [2022-03-12 01:40:04]:auto_derby.jobs.nurturing:69: score:	0.00/0.00:	Item<蹄鉄ハンマー・極#52@25>	
INFO  [2022-03-12 01:40:04]:auto_derby.jobs.nurturing:69: score:	0.00/0.00:	Item<効率練習のススメ#28@150>	
INFO  [2022-03-12 01:40:04]:auto_derby.jobs.nurturing:69: score:	0.00/0.00:	Item<スピードトレーニング嘆願書#37@150>	
```
不知道爲什麼全部物品分數都是 0，貌似因爲這樣才error?
```
INFO  [2022-03-12 01:40:07]:auto_derby.single_mode.context:336: next turn: Context<scenario=Make a new track!!  ～クライマックス開幕～,turn=72,mood=(1.2, 1.1),vit=0.357,spd=1102,sta=652,pow=705,gut=303,wis=343,fan=313551,ground=AE,distance=GEAA,style=GAAB,condition=0,pt=740,coin=213,items=14>
DEBUG [2022-03-12 01:40:07]:auto_derby.single_mode.item.item:166: Item<バイタル20#16x1> expected effect score: 0.00: 28.0 by price;-100% by turns;-10% by quantity;
ERROR [2022-03-12 01:40:07]:__main__:123: unexpected exception
Traceback (most recent call last):
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 119, in <module>
    main()
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 90, in main
    job()
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 311, in nurturing
    spec[_spec_key(tmpl)](ac)
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 167, in _ac_handle_turn
    _handle_turn(ac.ctx)
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 122, in _handle_turn
    command_plans = sorted(
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 123, in <genexpr>
    (_CommandPlan(ctx, i) for i in turn_commands),
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 98, in __init__
    self.item_score, self.items = item.plan.compute(ctx, command)
  File "D:\dev\auto-derby\auto_derby\single_mode\item\plan.py", line 51, in compute
    for i in sorted(
  File "D:\dev\auto-derby\auto_derby\single_mode\item\plan.py", line 25, in iterate
    s_e = item.expected_effect_score(ctx, command)
  File "D:\dev\auto-derby\auto_derby\single_mode\item\item.py", line 167, in expected_effect_score
    assert ret > 0, ret
AssertionError: 0.0
```

**Comment by NateScarlet** [comment]
正在处理重复效果 做到一半肯定用不了

**Comment by NateScarlet** [comment]
@Small-Ku 期望交换分现在可以是 0 了 你日志里的实际交换分为0是因为那些道具的效果还没做评分

**Comment by NateScarlet** [comment]
跑完一局 现在会配合命令使用道具且不会使用重复效果了 评分还需调整

物品识别错误会在商店卡死 相同物品不同价格没区分而且如果要买的物品超过持有上限也会卡死

**Comment by Small-Ku** [comment]
バイタル65/40/20 感覺特別容易搞混
貌似同一瓶バイタル20也可以分別識別出另外兩瓶了

**Comment by NateScarlet** [comment]
那我对数字结尾的物品调高点阈值

**Comment by NateScarlet** [comment]
@Small-Ku 也有可能是你自己选的时候没注意选错了

**Comment by NateScarlet** [comment]
スピードアンクルウェイト 和 スタミナアンクルウェイト 也容易搞混 调高了阈值 5e3cceeea9296956c10e29b550fe27fa95797f0f

**Comment by NateScarlet** [comment]
基本功能都实现了 预计下周发布

**Comment by Small-Ku** [comment]
![last_screenshot](https://user-images.githubusercontent.com/16464896/158426878-26377784-ff69-43cf-93a3-5693f65c95db.png)
這個出現的時候在找training，應該是未處理？

**Comment by NateScarlet** [comment]
@Small-Ku 发现是等单个图片有超时 但是等同一位置图片的时候没继承超时设置 所以一直无限等

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/158446780-88eaf2e2-8dd1-4775-a06a-47c947b1058d.png)

好像更新后点数不足的弹窗标题改了
