### ISSUE TITLE
是不是忘了加single_mode_go_out_option_left_top.pos.png了。。识别到奇怪的地方了

### ISSUE THREAD

**Issue by libaibaba** [NateScarlet/auto-derby#282]
DEBUG [14:45:21]:auto_derby.template:61: load: single_mode_go_out_option_left_top.pos.png
DEBUG [14:45:21]:auto_derby.template:78: can not load: single_mode_go_out_option_left_top.pos.png: 
DEBUG [14:45:21]:auto_derby.template:179: not match: tmpl=tmpl<single_mode_go_out_option_left_top.png>, pos=(264, 898), similarity=0.710
INFO  [14:45:21]:auto_derby.template:199: no match: tmpl=('single_mode_go_out_option_left_top.png',)
ERROR [14:45:21]:__main__:129: unexpected exception
Traceback (most recent call last):
  File "auto-derby-master\auto_derby\__main__.py", line 125, in <module>
    main()
  File "auto-derby-master\auto_derby\__main__.py", line 96, in main
    job()
  File "auto-derby-master\auto_derby\jobs\nurturing.py", line 328, in nurturing
    spec[_spec_key(tmpl)](ac)
  File "auto-derby-master\auto_derby\jobs\nurturing.py", line 179, in _ac_handle_turn
    _handle_turn(ac.ctx)
  File "auto-derby-master\auto_derby\jobs\nurturing.py", line 138, in _handle_turn
    command_plans[0].execute(ctx)
  File "auto-derby-master\auto_derby\jobs\nurturing.py", line 110, in execute
    self.command.execute(ctx)
  File "auto-derby-master\auto_derby\single_mode\commands\go_out.py", line 45, in execute
    self.option = next(
StopIteration
![last_screenshot](https://user-images.githubusercontent.com/52236285/161488426-6c2f207f-ff0b-42fa-8f0a-3507b74c3353.png)

**Comment by NateScarlet** [comment]
关闭所有操作确认再用脚本 不然我认为你就是想在出确认的时候停止脚本
