### ISSUE TITLE
URA育成 爱丽速子 シニア級7月後半 报错

### ISSUE THREAD

**Issue by cwbeta** [NateScarlet/auto-derby#294]
截图：
![last_screenshot](https://user-images.githubusercontent.com/8300417/163428325-b7c99778-655f-4722-b73d-3277b02fea60.png)

运行Plugins：
SSR樫本理子,auto_crane,no_event_prompt,no_ocr_prompt,no_item_prompt,limited_sale_buy_first_3

报错信息：
Traceback (most recent call last):
  File "D:\CODE\python\auto-derby\auto_derby\__main__.py", line 125, in <module>
    main()
  File "D:\CODE\python\auto-derby\auto_derby\__main__.py", line 96, in main
    job()
  File "D:\CODE\python\auto-derby\auto_derby\jobs\nurturing.py", line 328, in nurturing
    spec[_spec_key(tmpl)](ac)
  File "D:\CODE\python\auto-derby\auto_derby\jobs\nurturing.py", line 179, in _ac_handle_turn
    _handle_turn(ac.ctx)
  File "D:\CODE\python\auto-derby\auto_derby\jobs\nurturing.py", line 124, in _handle_turn
    turn_commands = tuple(commands.from_context(ctx))
  File "D:\CODE\python\auto-derby\auto_derby\single_mode\commands\_from_context.py", line 52, in from_context
    scene.recognize_v2(ctx)
  File "D:\CODE\python\auto-derby\auto_derby\scenes\single_mode\training.py", line 745, in recognize_v2
    self.trainings = tuple(
  File "D:\CODE\python\auto-derby\auto_derby\scenes\single_mode\training.py", line 746, in <genexpr>
    i.result()
  File "C:\Python38\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\CODE\python\auto-derby\auto_derby\scenes\single_mode\training.py", line 704, in _recognize_training
    self.skill += recognize(img.crop(bbox_group[5]))
  File "D:\CODE\python\auto-derby\auto_derby\scenes\single_mode\training.py", line 130, in _recognize_base_effect
    return int(text.lstrip("+"))
ValueError: invalid literal for int() with base 10: '2後'

**Comment by Small-Ku** [comment]
建議把debug文件夾連auto_derby.log一同發上來
這應該是OCR的問題，先關掉no_ocr_prompt試試吧

**Comment by cwbeta** [comment]
[debug.2.zip](https://github.com/NateScarlet/auto-derby/files/8493632/debug.2.zip)
打包上傳了，debug目錄裡single_mode_training_images看起來是每次訓練的截圖，佔空間很大，但應該用處不大，所以我沒有打在壓縮包裡。
我用no_ocr_prompt訓練了兩次愛麗速子，兩次都在外宿劇情裡出現了ocr報錯，ocr識別的內容和這次不一樣，可惜第一次我忘記備份debug信息了。

**Comment by Small-Ku** [comment]
single_mode_training_images 裏才有你這個報錯的圖片，畢竟現在識別是多工處理的。可以的話，下次還請把 training 的截圖也放上來，反而這個不是事件的報錯，不需要 event 的截圖呢。

**Comment by cwbeta** [comment]
这次带training目录了，文件比较大，上传到了奶牛快传：
传输链接：https://cowtransfer.com/s/457cdfc5cca543 或 打开【奶牛快传】cowtransfer.com 使用传输口令：ilnx96 提取；

**Comment by Small-Ku** [comment]
![e47cd147f8121874eaf7c7dc1437e](https://user-images.githubusercontent.com/16464896/163714864-c731f717-feb1-417f-a90a-b94bc5ac4cdd.png)
問題是這張的手太像文字了
![圖片](https://user-images.githubusercontent.com/16464896/163714873-1335cf8b-380e-4933-acca-0a97b956f9b4.png)

**Comment by cwbeta** [comment]
嗯，我育成了好多次，即使不用no_ item_ prompt也會有很高的概率會在這裡報錯退出，感覺是速子專有的報錯了。
可能在OCR識別數字的部分，如果識別成文字，就自動忽略會好一些？ 至少應該不會報錯。

**Comment by NateScarlet** [comment]
> 嗯，我育成了好多次，即使不用no_ item_ prompt也會有很高的概率會在這裡報錯退出，感覺是速子專有的報錯了。 可能在OCR識別數字的部分，如果識別成文字，就自動忽略會好一些？ 至少應該不會報錯。

不存在识别成文字 是提取文字会提取到手
直接改进提取方法就完了 没必要将识别错也视为合法情况 增加复杂度
