### ISSUE TITLE
育成中卡死

### ISSUE THREAD

**Issue by isisake-19** [NateScarlet/auto-derby#304]
Exception happened during processing of request from ('127.0.0.1', 50600)
Traceback (most recent call last):
  File "E:\新建文件夹\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\新建文件夹\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\新建文件夹\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\isisake\Desktop\auto-derby-master\auto_derby\web\handler.py", line 49, in handle
    return super().handle()
  File "E:\新建文件夹\lib\http\server.py", line 428, in handle
    self.handle_one_request()
  File "E:\新建文件夹\lib\http\server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
ValueError: readline of closed file

**Comment by NateScarlet** [comment]
发完整日志

推荐阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
