### ISSUE TITLE
训练失败率100%时ocr识别错误，将%识别为デ导致崩溃

### ISSUE THREAD

**Issue by crmccc** [NateScarlet/auto-derby#309]
版本 1.25
失败率100%时ocr识别错误，将%识别为デ，直接崩溃

log及截图如下:
![45c4ce9cd5cc528b01f92c070b986](https://user-images.githubusercontent.com/32813768/169005252-c4dca6f5-8ca9-4b71-8d98-5cd532371ce8.png)
![下载 (1)](https://user-images.githubusercontent.com/32813768/169005237-dbb5a589-e259-4151-b70e-a84af3f779ae.png)

```
DEBUG [2022-05-18 17:11:19]:auto_derby.ocr:336: image: caption=text width=69 height=48 layers=binary url=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEUAAAAwCAAAAABiCeiHAAABlUlEQVR4nO2T3XKcMAyFP8OGJJ3Mpnn/V2xnCWVZsGWpF7ZZYGnzAOHc2Prx0ZEtw4HvihBVNS4cvamaXGbbzOKv2VIAtyURU8NVdVUc1xcxXFV3P3NCVbVnSjj61x0lMsZPIE5aHBJvgOiU7E8PoJJ1yl47U4w9QBtjjkcZE1vwAIwBwELubo8EC/lGxpDEDOpzY5NdAMIVwBK19bss6ru884nFW7loEQ8weQCbAG4lVrGCs3NR5QaAMIt2WgOMVYoCNPUuy+97o8YpxUu9kN7zXYVWrAG0kKTUGfV9a6VAeayY7SaKuRrw05y8ZnmYnj3kUu2pmV3rjpRHuM1a8LY4umb5uOe6ciElo15lYsPC2LwRrvwQxwTzJQNPbqm0C2f+CQ23tGnz1InlGW59vC2lrI49aHlO65tLvQ2aFbzC4t/Fjv+g1+gBRtFcWWIEuJq/3tMkbGpvaEYa7e3Hk6/yOw6Nnnp5ftFqOUxfjURnMo7B/izUyzT6/P0yyfbQDunlhHwsHW3t4vsXxQ8cOHDgwHfFX//Cz/eblQroAAAAAElFTkSuQmCC
DEBUG [2022-05-18 17:11:19]:auto_derby.ocr:126: image: caption=query label: IHMQueryResult<85.2%,0,f00ff81f> by f00ff81f7c3c1e781ef00ff00ff00ff00ff00ff00ef01ef83e7cfc3ff81fe007 width=14 height=19 url=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAATCAAAAACFa2NIAAAAR0lEQVR4nJWPQQ4AMQgCB/7/Z3owuibbSz2gqBAVQAAQ4GGkWl8SblZzt6rATLSVphOHHeaF6jfNdTmgm1UGtKXC60Z1PU8esyUPInDLS0IAAAAASUVORK5CYII=
DEBUG [2022-05-18 17:11:19]:auto_derby.ocr:126: image: caption=query label: IHMQueryResult<86.7%,0,f007fc1f> by f81ffc3f3e3c1ff80ff00ff00ff00ff00ff00ff00ff00ff81f7cfe3ff81fe007 width=13 height=19 url=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAATCAAAAABuXNhLAAAAQklEQVR4nLXPMRKAAAwCwU3G/38Zixh17E0V4AooBCj6FsIhYwf6YsbojBi291NL3vevyjer3sKZPnki5b22lio4ATVsDiJea2/pAAAAAElFTkSuQmCC
DEBUG [2022-05-18 17:11:19]:auto_derby.ocr:126: image: caption=query label: IHMQueryResult<46.9%,デ,fc1ffc7f> by 7ec0ffe0fff0e770e738ff3cff1e7e0f1c078007c003c001e000f00070003000 width=17 height=18 url=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABEAAAASCAAAAACYkmqIAAAASUlEQVR4nJXOMQ7AMAgEwcH///OlCHFiK40pkFh0LEWgdGXIOyEkPJ3EsFZtJKwkaiPtSKTPg6HkXmaTzAdWj6/rIDNTR5k/cAEINR/55F4HXQAAAABJRU5ErkJggg==
WARNING[2022-05-18 17:11:19]:auto_derby.ocr:85: image: caption=using low similarity label: hash=7ec0ffe0fff0e770e738ff3cff1e7e0f1c078007c003c001e000f00070003000, value=デ, similarity=0.46875 width=17 height=18 url=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABEAAAASCAAAAACYkmqIAAAASUlEQVR4nJXOMQ7AMAgEwcH///OlCHFiK40pkFh0LEWgdGXIOyEkPJ3EsFZtJKwkaiPtSKTPg6HkXmaTzAdWj6/rIDNTR5k/cAEINR/55F4HXQAAAABJRU5ErkJggg==
DEBUG [2022-05-18 17:11:19]:auto_derby.ocr:341: ocr result: 00デ
ERROR [2022-05-18 17:11:19]:auto_derby.scenes.single_mode.training:725: image: caption=training recognition failed: Traceback (most recent call last):
  File "D:\project\auto-derby\auto_derby\scenes\single_mode\training.py", line 721, in _recognize_training
    self.failure_rate = _recognize_failure_rate(rp, self, img)
  File "D:\project\auto-derby\auto_derby\scenes\single_mode\training.py", line 294, in _recognize_failure_rate
    return int(text.strip("%")) / 100
ValueError: invalid literal for int() with base 10: '00デ'
 width=540 height=960
ERROR [2022-05-18 17:11:19]:__main__:141: unexpected exception: Traceback (most recent call last):
  File "D:\project\auto-derby\auto_derby\__main__.py", line 137, in <module>
    main()
  File "D:\project\auto-derby\auto_derby\__main__.py", line 106, in main
    job()
  File "D:\project\auto-derby\auto_derby\jobs\nurturing.py", line 327, in nurturing
    spec[_spec_key(tmpl)](ac)
  File "D:\project\auto-derby\auto_derby\jobs\nurturing.py", line 178, in _ac_handle_turn
    _handle_turn(ac.ctx)
  File "D:\project\auto-derby\auto_derby\jobs\nurturing.py", line 121, in _handle_turn
    turn_commands = tuple(commands.from_context(ctx))
  File "D:\project\auto-derby\auto_derby\single_mode\commands\_from_context.py", line 52, in from_context
    scene.recognize_v2(ctx)
  File "D:\project\auto-derby\auto_derby\scenes\single_mode\training.py", line 763, in recognize_v2
    self.trainings = tuple(
  File "D:\project\auto-derby\auto_derby\scenes\single_mode\training.py", line 764, in <genexpr>
    i.result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\project\auto-derby\auto_derby\scenes\single_mode\training.py", line 721, in _recognize_training
    self.failure_rate = _recognize_failure_rate(rp, self, img)
  File "D:\project\auto-derby\auto_derby\scenes\single_mode\training.py", line 294, in _recognize_failure_rate
    return int(text.strip("%")) / 100
ValueError: invalid literal for int() with base 10: '00デ'
```

[auto_derby.log](https://github.com/NateScarlet/auto-derby/files/8714920/auto_derby.log)
[launcher.log](https://github.com/NateScarlet/auto-derby/files/8714921/launcher.log)

**Comment by NateScarlet** [comment]
文本图片截得不够宽 加宽10像素就好了
