### ISSUE TITLE
更新後 OpenCV Error

### ISSUE THREAD

**Issue by Small-Ku** [NateScarlet/auto-derby#322]
應該不是模擬器畫面太小就會報Error吧
```
ERROR [2022-07-04 17:41:10]:__main__:142: unexpected exception: Traceback (most recent call last):
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 138, in <module>
    main()
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 107, in main
    job()
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 343, in nurturing
    tmpl, pos = action.wait_image(*spec.keys())
  File "D:\dev\auto-derby\auto_derby\action.py", line 46, in wait_image
    return next(template.match(app.device.screenshot(max_age=0), *tmpl))
  File "D:\dev\auto-derby\auto_derby\template.py", line 183, in match
    for j in _match_one(img, i):
  File "D:\dev\auto-derby\auto_derby\template.py", line 159, in _match_one
    _, max_val, _, max_loc = cv2.minMaxLoc(res, mask=mask)
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-kuwfz3h3\opencv\modules\core\src\matrix_iterator.cpp:71: error: (-215:Assertion failed) A.size == arrays[i0]->size in function 'cv::NAryMatIterator::init'
```
[auto-derby.zip](https://github.com/NateScarlet/auto-derby/files/9038321/auto-derby.zip)

**Comment by Small-Ku** [comment]
貌似只有將模擬器的螢幕大小也調成 540*960 才不會報錯

**Comment by Small-Ku** [comment]
貌似臨時把分辨率設為 540*960 就可以了

**Comment by Small-Ku** [comment]
但是體力條識別也會報錯
```
Traceback (most recent call last):
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 138, in <module>
    main()
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 107, in main
    job()
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 346, in nurturing
    spec[_spec_key(tmpl)](ac)
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 197, in _ac_handle_turn
    _handle_turn(ac.ctx)
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 132, in _handle_turn
    scene.recognize(ctx)
  File "D:\dev\auto-derby\auto_derby\scenes\single_mode\command.py", line 202, in recognize
    action.run_with_retry(
  File "D:\dev\auto-derby\auto_derby\action.py", line 84, in run_with_retry
    return run_with_retry(fn, max_retry - 1, delay)
  File "D:\dev\auto-derby\auto_derby\action.py", line 84, in run_with_retry
    return run_with_retry(fn, max_retry - 1, delay)
  File "D:\dev\auto-derby\auto_derby\action.py", line 84, in run_with_retry
    return run_with_retry(fn, max_retry - 1, delay)
  [Previous line repeated 7 more times]
  File "D:\dev\auto-derby\auto_derby\action.py", line 79, in run_with_retry
    return fn()
  File "D:\dev\auto-derby\auto_derby\scenes\single_mode\command.py", line 197, in _recognize_static_with_retry
    _recognize_static()
  File "D:\dev\auto-derby\auto_derby\scenes\single_mode\command.py", line 187, in _recognize_static
    ctx.update_by_command_scene(app.device.screenshot())
  File "D:\dev\auto-derby\auto_derby\single_mode\context.py", line 389, in update_by_command_scene
    self.vitality = _recognize_vitality(screenshot.crop(vitality_bbox))
  File "D:\dev\auto-derby\auto_derby\single_mode\context.py", line 113, in _recognize_vitality
    return 1 - np.average(np.apply_along_axis(_is_empty, 1, cv_img[0, :]))
  File "<__array_function__ internals>", line 5, in apply_along_axis
  File "D:\Users\small\scoop\apps\python38\current\lib\site-packages\numpy\lib\shape_base.py", line 379, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
  File "D:\dev\auto-derby\auto_derby\single_mode\context.py", line 107, in _is_empty
    assert v.shape == (3,), v.shape
AssertionError: (4,)
```
[auto-derby.zip](https://github.com/NateScarlet/auto-derby/files/9038856/auto-derby.zip)
