### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file 

### ISSUE THREAD

**Issue by Lover-v** [NateScarlet/auto-derby#325]
纯萌新
INFO  [18:36:01]:__main__:26: auto_derby: 1.26.3 (2022-07-02 23:53:10)
INFO  [18:36:01]:auto_derby.infrastructure.web_log_service:102: web log service start at:       http://127.0.0.1:8400
INFO  [18:36:02]:auto_derby.web.handler:74: "GET / HTTP/1.1" 200 -
INFO  [18:36:02]:auto_derby.web.handler:74: "GET /log HTTP/1.1" 200 -
INFO  [18:36:02]:auto_derby.web.handler:74: "GET /favicon.ico HTTP/1.1" 200 -
ERROR [18:36:09]:__main__:142: unexpected exception: Traceback (most recent call last):
  File "E:\support\auto-derby\auto_derby\__main__.py", line 138, in <module>
    main()
  File "E:\support\auto-derby\auto_derby\__main__.py", line 107, in main
    job()
  File "E:\support\auto-derby\auto_derby\jobs\nurturing.py", line 343, in nurturing
    tmpl, pos = action.wait_image(*spec.keys())
  File "E:\support\auto-derby\auto_derby\action.py", line 46, in wait_image
    return next(template.match(app.device.screenshot(max_age=0), *tmpl))
  File "E:\support\auto-derby\auto_derby\infrastructure\client_device_service.py", line 44, in screenshot
    new_img = self._c.screenshot()
  File "E:\support\auto-derby\auto_derby\clients\adb.py", line 147, in screenshot
    return self._screenshot()
  File "E:\support\auto-derby\auto_derby\clients\adb.py", line 85, in _screenshot_init
    img = screenshot_method()
  File "E:\support\auto-derby\auto_derby\clients\adb.py", line 121, in _screenshot_png
    img = PIL.Image.open(io.BytesIO(img_data))
  File "C:\Users\flhs\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py", line 2967, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001AA7A226AE0>

错误代码如上，按照百度重装的pillow仍然报错，希望大佬救救

**Comment by NateScarlet** [comment]
如果什么都不懂别用实验性功能 用DMM版

推荐阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
