### ISSUE TITLE
使用power shall開啟腳本正常 但如果使用launcher.cmd 啟動就會報錯

### ISSUE THREAD

**Issue by deepseareo** [NateScarlet/auto-derby#337]
[launcher.log](https://github.com/NateScarlet/auto-derby/files/9172741/launcher.log)

Traceback (most recent call last):

  File "C:\Users\雷歐\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\雷歐\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 143, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\雷歐\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "F:\auto-derby-1.27.1\auto_derby\__init__.py", line 2, in <module>
    from ._config import config
  File "F:\auto-derby-1.27.1\auto_derby\_config.py", line 60, in <module>
    class config:
  File "F:\auto-derby-1.27.1\auto_derby\_config.py", line 125, in config
    single_mode_target_training_levels = _parse_training_levels(
  File "F:\auto-derby-1.27.1\auto_derby\_config.py", line 32, in _parse_training_levels
    ret[k] = int(v)
ValueError: invalid literal for int() with base 10: ' '

F:\auto-derby-1.27.1>

**Comment by NateScarlet** [comment]
目标训练级别里面不要填多余的空格
