### ISSUE TITLE
ア和ァ太相似

### ISSUE THREAD

**Issue by Small-Ku** [NateScarlet/auto-derby#52]
![last_screenshot local](https://user-images.githubusercontent.com/16464896/121867668-c7424500-cd32-11eb-8f27-a914a5ee630a.png)
```
DEBUG [2021-06-14 17:02:37]:auto_derby.ocr:65: match label: value=フ, current=ff3fffffffffffff00f800f8007c003c003e001f801fc007f003f801f8007000, match=ff7ffffffffff7f100f000f8007c007c003e003f801fc007f803f801f8007800, similarity=0.922
DEBUG [2021-06-14 17:02:37]:auto_derby.ocr:65: match label: value=ア, current=feffffff3efe007c007ce03fe03ff01ff01ff00ff80078007c003c003e001e00, match=ffffffffffff007c0078003ce03ff01ff01ff007f00078007c007c003e001e00, similarity=0.891
DEBUG [2021-06-14 17:02:37]:auto_derby.ocr:65: match label: value=イ, current=00f000f800fc007fc03fe00ffc0ffe0fff0f1f0f020f000f000f000f000f000f, match=00f000f800fc007f801fe00ffc07ff07ff073f07000700070007000700070007, similarity=0.883
DEBUG [2021-06-14 17:02:37]:auto_derby.ocr:65: match label: value=ナ, current=8007c007c003c007ffffffffffffc007c003c003e003e001f001f800f8007800, match=000380038007800ffe7fffffffffe007c003c003e003f001f801f800f8007800, similarity=0.898
DEBUG [2021-06-14 17:02:37]:auto_derby.ocr:65: match label: value=ル, current=8001c001dc01dc019c019e019e01dee1def1def99e7f8f3f8f1fc70fc703c601, match=c00180019c019c019c019e019e01dee1def1def9de7fce3fcf1fc70fc707c401, similarity=0.922
DEBUG [2021-06-14 17:02:37]:auto_derby.ocr:65: match label: value=ズ, current=0c0efe2ffcff00ff800f80078003c003e007f00ff00ffc1f7e3e1f3c0f380630, match=1c07fe6ffcff00ff000f80078003c003e007f00ff00ffc1f3e3e1f3c0f380630, similarity=0.953
DEBUG [2021-06-14 17:02:37]:auto_derby.ocr:65: match label: value=開, current=3e7c777e636673667f7e7f7e07600340e347e347e347e347f37f737e337e0030, match=3c3c7e7e7ffe7ffe7ffe3ffe07e003c063c263c673c6f3fff3ff73fe02760000, similarity=0.656
INFO  [2021-06-14 17:02:47]:auto_derby.ocr:82: labeled: hash=3e7c777e636673667f7e7f7e07600340e347e347e347e347f37f737e337e0030, value=開
DEBUG [2021-06-14 17:02:47]:auto_derby.ocr:88: use label: hash=3e7c777e636673667f7e7f7e07600340e347e347e347e347f37f737e337e0030, value=開
DEBUG [2021-06-14 17:02:47]:auto_derby.ocr:65: match label: value=催, current=1844fcefcc7fcc19ce19ce3fce1dfe1dfc3ffc1cfc1ccc3dcc3dcc1ccc1c801c, match=3844fceecc7fce00ce00cf7fcf3cce1cfc7ffc3dfc18cc3dcc3c4c18cc3c843d, similarity=0.781
INFO  [2021-06-14 17:02:52]:auto_derby.ocr:82: labeled: hash=1844fcefcc7fcc19ce19ce3fce1dfe1dfc3ffc1cfc1ccc3dcc3dcc1ccc1c801c, value=催
DEBUG [2021-06-14 17:02:52]:auto_derby.ocr:88: use label: hash=1844fcefcc7fcc19ce19ce3fce1dfe1dfc3ffc1cfc1ccc3dcc3dcc1ccc1c801c, value=催
DEBUG [2021-06-14 17:02:52]:auto_derby.ocr:65: match label: value=中, current=8001e003ff7fff7fff7fc76187418761c761ef73ff7fff7fc661800180018001, match=8001c003ff7fff7fff7fc361836083608761ef73ff7fcffb8761800180018001, similarity=0.891
DEBUG [2021-06-14 17:02:52]:auto_derby.ocr:247: ocr result: フアイナルズ開催中
ERROR [2021-06-14 17:02:52]:__main__:107: unexpected exception
Traceback (most recent call last):
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 105, in <module>
    main()
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 64, in main
    job()
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 302, in nurturing
    _update_context_by_command_scene(ctx)
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 243, in _update_context_by_command_scene
    ctx.update_by_command_scene(template.screenshot(max_age=0))
  File "D:\dev\auto-derby\auto_derby\single_mode\context.py", line 236, in update_by_command_scene
    self.date = _ocr_date(screenshot.crop(date_bbox))
  File "D:\dev\auto-derby\auto_derby\single_mode\context.py", line 41, in _ocr_date
    year_end = text.index("級") + 1
ValueError: substring not found
```
這個匹配的 ocr label 貌似不是我新增的，貌似把ァ的 label 加進去就好了
`"feffffff3efe007c007ce03fe03ff01ff01ff00ff80078007c003c003e001e00": "ァ"`

**Comment by NateScarlet** [comment]
这样处理就是对的 当前版本的 ocr 会根据其他文字的高度尽量保留空白
