### ISSUE TITLE
麥昆的寶塚紀念

### ISSUE THREAD

**Issue by Small-Ku** [NateScarlet/auto-derby#58]
跑到第三年六月後半，寶塚紀念時崩潰了
貌似是因爲場地換了？
```
ERROR [2021-06-16 15:02:08]:__main__:108: unexpected exception
Traceback (most recent call last):
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 106, in <module>
    main()
  File "D:\dev\auto-derby\auto_derby\__main__.py", line 65, in main
    job()
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 311, in nurturing
    _handle_race(ctx)
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 207, in _handle_race
    race1 = race1 or _current_race(ctx)
  File "D:\dev\auto-derby\auto_derby\jobs\nurturing.py", line 30, in _current_race
    race1 = race.find_by_race_detail_image(ctx, template.screenshot())
  File "D:\dev\auto-derby\auto_derby\single_mode\race.py", line 547, in find_by_race_detail_image
    raise ValueError("find_by_race_details_image: can race match spec: %s", full_spec)
ValueError: ('find_by_race_details_image: can race match spec: %s', ('京都', 1, 2200, 1, 3, 15000))
```
![last_screenshot local](https://user-images.githubusercontent.com/16464896/122173343-3c895380-ceb4-11eb-8d90-4e30bc75e07b.png)

**Comment by NateScarlet** [comment]
特别比赛我没提取 之前好像在数据库里面看到了
