### ISSUE TITLE
点击位置出现偏差

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#63]
![last_screenshot local](https://user-images.githubusercontent.com/37131177/122439461-4010fd80-cfce-11eb-8d30-cec41f83e7a5.png)
- 最后截图如上所示
- 卡住之前最后的log如下
```
DEBUG [2021-06-18 00:47:16]:auto_derby.template:41: screenshot
DEBUG [2021-06-18 00:47:16]:auto_derby.template:55: load: return_button.pos.png
DEBUG [2021-06-18 00:47:16]:auto_derby.template:71: can not load: return_button.pos.png: [Errno 2] No such file or directory: 'E:\\auto-derby\\auto_derby\\templates\\return_button.pos.png'
DEBUG [2021-06-18 00:47:16]:auto_derby.template:55: load: return_button.png
DEBUG [2021-06-18 00:47:16]:auto_derby.template:117: lightness match: tmpl=tmpl<return_button.png>, similarity=1.000
INFO  [2021-06-18 00:47:16]:auto_derby.template:162: match: tmpl=tmpl<return_button.png>, pos=(42, 911), similarity=0.97
DEBUG [2021-06-18 00:47:16]:auto_derby.template:41: screenshot
DEBUG [2021-06-18 00:47:16]:auto_derby.template:55: load: single_mode_command_race.pos.png
DEBUG [2021-06-18 00:47:16]:auto_derby.template:55: load: single_mode_command_race.png
DEBUG [2021-06-18 00:47:16]:auto_derby.template:117: lightness match: tmpl=tmpl<single_mode_command_race.png>, similarity=0.957
INFO  [2021-06-18 00:47:16]:auto_derby.template:162: match: tmpl=tmpl<single_mode_command_race.png>, pos=(379, 860), similarity=0.95
DEBUG [2021-06-18 00:47:17]:auto_derby.template:55: load: single_mode_continuous_race_title.pos.png
DEBUG [2021-06-18 00:47:17]:auto_derby.template:71: can not load: single_mode_continuous_race_title.pos.png: [Errno 2] No such file or directory: 'E:\\auto-derby\\auto_derby\\templates\\single_mode_continuous_race_title.pos.png'
DEBUG [2021-06-18 00:47:17]:auto_derby.template:55: load: single_mode_continuous_race_title.png
DEBUG [2021-06-18 00:47:17]:auto_derby.template:158: not match: tmpl=tmpl<single_mode_continuous_race_title.png>, pos=(145, 893), similarity=0.469
INFO  [2021-06-18 00:47:17]:auto_derby.template:178: no match: tmpl=('single_mode_continuous_race_title.png',)
WARNING[2021-06-18 00:47:19]:auto_derby.window:113: recover foreground window failed: (1400, 'SetForegroundWindow', '无效的窗口句柄。')
DEBUG [2021-06-18 00:47:20]:auto_derby.template:41: screenshot
DEBUG [2021-06-18 00:47:20]:auto_derby.template:55: load: single_mode_race_detail_button.pos.png
DEBUG [2021-06-18 00:47:20]:auto_derby.template:55: load: single_mode_race_detail_button.png
DEBUG [2021-06-18 00:47:20]:auto_derby.template:158: not match: tmpl=tmpl<single_mode_race_detail_button.png>, pos=(495, 354), similarity=0.000
INFO  [2021-06-18 00:47:20]:auto_derby.template:178: no match: tmpl=(tmpl<single_mode_race_detail_button.png>,)
DEBUG [2021-06-18 00:47:20]:auto_derby.template:41: screenshot
DEBUG [2021-06-18 00:47:20]:auto_derby.template:158: not match: tmpl=tmpl<single_mode_race_detail_button.png>, pos=(495, 354), similarity=0.000
INFO  [2021-06-18 00:47:20]:auto_derby.template:178: no match: tmpl=(tmpl<single_mode_race_detail_button.png>,)
```
- 重新启动auto-derby可以复现。

**Comment by NateScarlet** [comment]
什么版本 好像和 #57 是同一个问题

**Comment by fatinghenji** [comment]
怎么查看版本号？我是在北京时间2021-06-1719：53分pull的源码。

**Comment by NateScarlet** [comment]
你用启动器的话日志和标题都有

或者你手动运行 `git describe --dirty --always `

**Comment by fatinghenji** [comment]
7fd912e-dirty

**Comment by NateScarlet** [comment]
你 pull 的应该是主分支 这个问题我 30 分钟前刚从开发分支合并过来

**Comment by fatinghenji** [comment]
我重新pull一下试试

**Comment by fatinghenji** [comment]
pull了之后出现新的错误
```
DEBUG [2021-06-18 01:01:57]:auto_derby.plugin:43: loaded: example_custom_context, example_custom_race_score, example_custom_training_score, hello_world
ERROR [2021-06-18 01:01:57]:__main__:107: unexpected exception
Traceback (most recent call last):
  File "E:\auto-derby\auto_derby\__main__.py", line 103, in <module>
    main()
  File "E:\auto-derby\auto_derby\__main__.py", line 46, in main
    plugin.install(i)
  File "E:\auto-derby\auto_derby\plugin.py", line 47, in install
    g.plugins[name].install()
KeyError: ''
```
貌似是因为没有选择plugins？plugins文件夹里的文件里能否加上`//说明`或`#说明`指导下怎么调用？
