### ISSUE TITLE
不使用插件时初始化失败

### ISSUE THREAD

**Issue by NateScarlet** [NateScarlet/auto-derby#64]
pull了之后出现新的错误
```
DEBUG [2021-06-18 01:01:57]:auto_derby.plugin:43: loaded: example_custom_context, example_custom_race_score, example_custom_training_score, hello_world
ERROR [2021-06-18 01:01:57]:__main__:107: unexpected exception
Traceback (most recent call last):
  File "E:\auto-derby\auto_derby\__main__.py", line 103, in <module>
    main()
  File "E:\auto-derby\auto_derby\__main__.py", line 46, in main
    plugin.install(i)
  File "E:\auto-derby\auto_derby\plugin.py", line 47, in install
    g.plugins[name].install()
KeyError: ''
```
貌似是因为没有选择plugins？plugins文件夹里的文件里能否加上`//说明`或`#说明`指导下怎么调用？

_Originally posted by @fatinghenji in https://github.com/NateScarlet/auto-derby/issues/63#issuecomment-863411089_

**Comment by NateScarlet** [comment]
@fatinghenji

什么说明 我代码用了严格类型检查 光看函数参数命名就应该能懂 

你想干啥 我只能多写几个 example

**Comment by NateScarlet** [comment]
![图片](https://user-images.githubusercontent.com/21083014/122443918-9e3fdf80-cfd2-11eb-93ec-922a443c4855.png)
难道你没用IDE的吗 用 vscode 官方 python 插件有完整的代码提示
