### ISSUE TITLE
[dev]launcher无法启动脚本

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#68]
已经安装了新的依赖，log文件入下：
[launcher.zip](https://github.com/NateScarlet/auto-derby/files/6681697/launcher.zip)

**Comment by NateScarlet** [comment]
你确定是无法启动launcher而不是无法启动脚本?这日志包含了你点start才会出现的信息

看 auto_derby.log

**Comment by fatinghenji** [comment]
auto_derby.log还停留在6.19的凌晨
![image](https://user-images.githubusercontent.com/37131177/122661746-4e267000-d1c0-11eb-8629-2665c892a394.png)

**Comment by NateScarlet** [comment]
那你用命令行的方式开脚本试下

`py -3.8 -m auto_derby --adb 127.0.0.1:5555 nurturing `

或者是日志文件被其它程序占用了

**Comment by fatinghenji** [comment]
报错如下：
```cmd
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "E:\自动养马\auto_derby\__init__.py", line 1, in <module>
    from ._config import config
  File "E:\自动养马\auto_derby\_config.py", line 60, in <module>
    config.apply()
  File "E:\自动养马\auto_derby\_config.py", line 55, in apply
    ocr.reload()
  File "E:\自动养马\auto_derby\ocr.py", line 31, in reload
    g.labels = json.load(f)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 658 column 1 (char 49202)
```

**Comment by NateScarlet** [comment]
你的ocr_labels.json数据格式不合法

**Comment by fatinghenji** [comment]
解决了
