### ISSUE TITLE
[dev]识别比赛错误

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#81]
报错log：
```POWERSHELL
Traceback (most recent call last):
  File "E:\AAA\auto-derby\auto_derby\__main__.py", line 115, in <module>
    main()
  File "E:\AAA\auto-derby\auto_derby\__main__.py", line 87, in main
    job()
  File "E:\AAA\auto-derby\auto_derby\jobs\nurturing.py", line 305, in nurturing
    _handle_race(ctx)
  File "E:AAA\auto-derby\auto_derby\jobs\nurturing.py", line 201, in _handle_race
    race1 = race1 or _current_race(ctx)
  File "E:\AAA\auto-derby\auto_derby\jobs\nurturing.py", line 29, in _current_race
    race1 = race.find_by_race_detail_image(ctx, template.screenshot())
  File "E:\AAA\auto-derby\auto_derby\single_mode\race.py", line 792, in find_by_race_detail_image
    raise ValueError("find_by_race_details_image: can race match spec: %s", full_spec)
ValueError: ('find_by_race_details_image: can race match spec: %s', ('京都', 1, 2200, 1, 3, 15000))
```
用的是96c08ee，看起来像是ocr错误，我不知道怎么修……
![last_screenshot local](https://user-images.githubusercontent.com/37131177/123296288-18c7ac80-d549-11eb-895f-80589ddadb0d.png)

**Comment by NateScarlet** [comment]
宝塚記念正常应该是在阪神举办的 你马娘特殊剧情改了场地

需要我导入额外数据，暂时先手动处理这回合

Duplicate of #58
