### ISSUE TITLE
[dev]ura前日期中不包含“级”导致脚本出错

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#82]
报错如下：
```powershell
DEBUG [00:25:18]:auto_derby.template:45: screenshot
DEBUG [00:25:18]:auto_derby.template:177: not match: tmpl=tmpl<connecting.png>, pos=(390, 55), similarity=0.168
DEBUG [00:25:18]:auto_derby.template:177: not match: tmpl=tmpl<retry_button.png>, pos=(152, 925), similarity=0.395
DEBUG [00:25:18]:auto_derby.template:122: lightness match: tmpl=tmpl<single_mode_command_training.png>, similarity=0.984
INFO  [00:25:18]:auto_derby.template:181: match: tmpl=tmpl<single_mode_command_training.png>, pos=(199, 760), similarity=0.98
DEBUG [00:25:20]:auto_derby.template:45: screenshot
DEBUG [00:25:21]:auto_derby.template:122: lightness match: tmpl=tmpl<single_mode_character_detail_button.png>, similarity=1.000
INFO  [00:25:21]:auto_derby.template:181: match: tmpl=tmpl<single_mode_character_detail_button.png>, pos=(466, 559), similarity=0.91
DEBUG [00:25:21]:auto_derby.ocr:64: match label: value=フ, current=ffffffffff7f00780078003c003c003e001f801fc00fe007f803f801f8007000, match=fffffffffeff00fc00780038003c003e003f001fc00fe007f003f801f8007000, similarity=0.938
DEBUG [00:25:21]:auto_derby.ocr:64: match label: value=ア, current=ffffffffffffff7fe07cc03ce03de01fe00ff000f800f8007c003c003c001800, match=fffffffffffffffb0078e078f03ff01ff01ff004f80078003c003c001e000800, similarity=0.844
DEBUG [00:25:21]:auto_derby.ocr:64: match label: value=イ, current=006000f800fc007e803fe01ff80ffe0fff0fbf0f060f000f000f000f000f000f, match=00f000f800fc007f801fe00ffc07ff07ff073f07000700070007000700070007, similarity=0.844
DEBUG [00:25:21]:auto_derby.ocr:64: match label: value=ナ, current=8007800780078007ffffffffffffc007c003c003e003e001f801f80078003800, match=000380038007800ffe7fffffffffe007c003c003e003f001f801f800f8007800, similarity=0.922
DEBUG [00:25:21]:auto_derby.ocr:64: match label: value=ル, current=80018803fc03fc03fc03fc03fc039ec39ee39ef38e7f8e3f871f870786038001, match=800380039c03bc03bc03bc039c039cc39ee39ef39e7f8e3f8f1f8f0f86038001, similarity=0.891
DEBUG [00:25:21]:auto_derby.ocr:64: match label: value=ズ, current=fc0ffe5ffcff007f000780078007c003e007f007f80f7c1e3e3e1f7c0f380210, match=1c07fe6ffcff00ff000f80078003c003e007f00ff00ffc1f3e3e1f3c0f380630, similarity=0.875
DEBUG [00:25:21]:auto_derby.ocr:64: match label: value=開, current=00003f7c7ffe67e667e67ff62ff003e003e0e3e7e3e7e3e7f3ef63e627f60260, match=3c3c7e7e7ffe7ffe7ffe3ffe07e003c063c263c673c6f3fff3ff73fe02760000, similarity=0.609
Corresponding text for current displaying image:開
INFO  [00:25:50]:auto_derby.ocr:80: labeled: hash=00003f7c7ffe67e667e67ff62ff003e003e0e3e7e3e7e3e7f3ef63e627f60260, value=開
DEBUG [00:25:50]:auto_derby.ocr:86: use label: hash=00003f7c7ffe67e667e67ff62ff003e003e0e3e7e3e7e3e7f3ef63e627f60260, value=開
DEBUG [00:25:50]:auto_derby.ocr:64: match label: value=催, current=00006ce6eeffce7fcf1dcf3fcf3fef1cfe18fe18ee18ee1cce1cce08c61cc47f, match=00044c6eccffce1fce1dcf7fcf7ffe1cfc1cfc1cfc18ec1ccc1ccc7fc47f0000, similarity=0.664
Corresponding text for current displaying image:催
INFO  [00:25:54]:auto_derby.ocr:80: labeled: hash=00006ce6eeffce7fcf1dcf3fcf3fef1cfe18fe18ee18ee1cce1cce08c61cc47f, value=催
DEBUG [00:25:54]:auto_derby.ocr:86: use label: hash=00006ce6eeffce7fcf1dcf3fcf3fef1cfe18fe18ee18ee1cce1cce08c61cc47f, value=催
DEBUG [00:25:54]:auto_derby.ocr:64: match label: value=中, current=8001c001ee7fffffffffc7e383e183e1c7f1ffffffffffffc2438001c0018001, match=0000c003feffffffffff87e183c187c187e7ffffffffeff7c003800180010000, similarity=0.836
DEBUG [00:25:54]:auto_derby.ocr:256: ocr result: フアイナルズ開催中
ERROR [00:25:54]:__main__:119: unexpected exception
Traceback (most recent call last):
    File "E:\AAA\auto-derby\auto_derby\__main__.py", line 115, in <module>
    main()
  File "E:AAA\auto-derby\auto_derby\__main__.py", line 87, in main
    job()
  File "E:AAA\auto-derby\auto_derby\jobs\nurturing.py", line 313, in nurturing
    _update_context_by_command_scene(ctx)
  File "E:\AAA\auto-derby\auto_derby\jobs\nurturing.py", line 260, in _update_context_by_command_scene
    ctx.update_by_command_scene(template.screenshot(max_age=0))
  File "E:\AAA\auto-derby\auto_derby\single_mode\context.py", line 270, in update_by_command_scene
    self.date = _ocr_date(screenshot.crop(date_bbox))
  File "E:\AAA\auto-derby\auto_derby\single_mode\context.py", line 47, in _ocr_date
    year_end = text.index("級") + 1
ValueError: substring not found
```
和刚刚那个bug的原因一样吗？
![last_screenshot local](https://user-images.githubusercontent.com/37131177/123299925-94772880-d54c-11eb-883e-4ccd186e56b5.png)

**Comment by NateScarlet** [comment]
手动标记 ffffffffffffff7fe07cc03ce03de01fe00ff000f800f8007c003c003c001800 为小写ァ

Duplicate of #52
