### ISSUE TITLE
[DEV]launcher无法启动脚本

### ISSUE THREAD

**Issue by WisdomDevils** [NateScarlet/auto-derby#84]
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python38\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\Program Files (x86)\Python\Python38\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "D:\Program Files (x86)\Python\Python38\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\WisdomDevil\Desktop\auto-derby-master\auto_derby\__init__.py", line 1, in <module>
    from ._config import config
  File "C:\Users\WisdomDevil\Desktop\auto-derby-master\auto_derby\_config.py", line 6, in <module>
    from auto_derby.single_mode.training import Training
  File "C:\Users\WisdomDevil\Desktop\auto-derby-master\auto_derby\single_mode\__init__.py", line 1, in <module>
    from .context import Context
  File "C:\Users\WisdomDevil\Desktop\auto-derby-master\auto_derby\single_mode\context.py", line 8, in <module>
    import cast_unknown as cast
ModuleNotFoundError: No module named 'cast_unknown'

C:\Users\WisdomDevil\Desktop\auto-derby-master>
报错界面如上

**Comment by NateScarlet** [comment]
你没装依赖

https://github.com/NateScarlet/auto-derby/blob/master/README.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by WisdomDevils** [comment]
要如何安装依赖呢

**Comment by NateScarlet** [comment]
README.md 写了

**Comment by WisdomDevils** [comment]
我感觉我应该是做错了
在python界面输入会出现这个结果
>>> py -3.8 -m pip install -r requirements.txt
  File "<stdin>", line 1
    py -3.8 -m pip install -r requirements.txt
               ^
SyntaxError: invalid syntax
>>>

**Comment by NateScarlet** [comment]
这是命令行命令 直接在你的shell里面运行(cmd/powershell/...)

**Comment by WisdomDevils** [comment]
感谢！现在界面在显示下载了！
