### ISSUE TITLE
[DEV]使用adb调试的时候报错

### ISSUE THREAD

**Issue by fatinghenji** [NateScarlet/auto-derby#90]
无线log如下：
```cmd
DEBUG [23:22:51]:auto_derby.plugin:43: loaded: example_custom_context, example_custom_race_score, example_custom_training_score, hello_world, limited_sale_buy_everything, use_legacy_screenshot
ERROR [23:22:51]:__main__:119: unexpected exception
Traceback (most recent call last):
  File "E:\auto\auto-derby\auto_derby\__main__.py", line 115, in <module>
    main()
  File "E:\auto\auto-derby\auto_derby\__main__.py", line 85, in main
    c.setup()
  File "E:\auto\auto-derby\auto_derby\clients\adb.py", line 77, in setup
    self.connect()
  File "E:\auto\auto-derby\auto_derby\clients\adb.py", line 50, in connect
    self.device.connect(rsa_keys=[signer])
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\adb_shell\adb_device.py", line 251, in connect
    cmd, arg0, arg1, banner = self._read([constants.AUTH, constants.CNXN], adb_info)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\adb_shell\adb_device.py", line 872, in _read
    raise exceptions.InvalidCommandError("Unknown command: %d = '%s' (arg0 = %d, arg1 = %d, msg = '%s')" % (cmd, int_to_cmd(cmd), arg0, arg1, msg))
adb_shell.exceptions.InvalidCommandError: Unknown command: 1397511251 = 'b'STLS'' (arg0 = 16777216, arg1 = 0, msg = 'b'STLS\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\xab\xb3\xac'')
```
有线log如下:
```cmd
DEBUG [2021-07-04 23:21:46]:auto_derby.plugin:43: loaded: example_custom_context, example_custom_race_score, example_custom_training_score, hello_world, limited_sale_buy_everything, use_legacy_screenshot
ERROR [2021-07-04 23:21:46]:__main__:119: unexpected exception
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\adb_shell\adb_message.py", line 120, in unpack
    cmd, arg0, arg1, data_length, data_checksum, _ = struct.unpack(constants.MESSAGE_FORMAT, message)
struct.error: unpack requires a buffer of 24 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\auto\auto-derby\auto_derby\__main__.py", line 115, in <module>
    main()
  File "E:\auto\auto-derby\auto_derby\__main__.py", line 85, in main
    c.setup()
  File "E:\auto\auto-derby\auto_derby\clients\adb.py", line 77, in setup
    self.connect()
  File "E:\auto\auto-derby\auto_derby\clients\adb.py", line 50, in connect
    self.device.connect(rsa_keys=[signer])
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\adb_shell\adb_device.py", line 251, in connect
    cmd, arg0, arg1, banner = self._read([constants.AUTH, constants.CNXN], adb_info)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\adb_shell\adb_device.py", line 868, in _read
    cmd, arg0, arg1, data_length, data_checksum = unpack(msg)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python38\lib\site-packages\adb_shell\adb_message.py", line 122, in unpack
    raise ValueError('Unable to unpack ADB command. (length={})'.format(len(message)), constants.MESSAGE_FORMAT, message, e)
ValueError: ('Unable to unpack ADB command. (length=0)', b'<6I', b'', error('unpack requires a buffer of 24 bytes'))
```
### 我在使用Windows11，是否和这个有关系？

**Comment by NateScarlet** [comment]
如果你直接用 adb 命令不能连接 说明是你配置的问题 如果能

那就是 https://github.com/JeffLIrion/adb_shell 的问题

没有什么我能做的

**Comment by fatinghenji** [comment]
> 那就是 https://github.com/JeffLIrion/adb_shell 的问题

确实是他那边的问题，看到有人在那边开相同的issue了。~他给的解决方案好像还是有问题~

**Comment by fatinghenji** [comment]
@NateScarlet 
adb_shelL那边提了个[问题](https://github.com/JeffLIrion/adb_shell/issues/152#issuecomment-877276248)，我不知道怎么回答……回来问问您。
> ### Question
> Are you supplying a key when you connect, as demonstrated in the README? Also, maybe it would work if you copy a key pair that has already been accepted (e.g., connect using the adb binary, disconnect, and then try to connect using this package with the key that adb used)?

**Comment by NateScarlet** [comment]
我在那边回了

key 都是自动生成的 默认是项目目录下 adb.local.key 和 adb.local.ley.pub

我不知道 adb 的密钥对在哪 你可以找了替换下再试试

**Comment by fatinghenji** [comment]
> 我不知道 adb 的密钥对在哪 你可以找了替换下再试试

目录是
```
C:\Users\{username}\.android\adbkey
C:\Users\{username}\.android\adbkey.pub
```
替换了，貌似没有什么作用，还是相同的错误。但是我不知道和文件的后缀有没有联系什么的，因为系统那边是`adbkey`，项目目录下是`*.key`。~感觉应该是一样的，因为打开之后看起来差不多~

**Comment by NateScarlet** [comment]
后缀没影响 只要能读取就行
